version: "3"
services:
    ecakeshop-sql:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        restart: unless-stopped
        environment:
            SA_PASSWORD: "QWElkj132!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        ports:
            - 1401:1433
        networks:
            - ecakeshopnet

    ecakeshop-api:
        restart: unless-stopped
        build: .
        environment:
            - ConnectionStrings:eCakeShop=Server=ecakeshop-sql,1433;Database=eCakeShop;User=sa;Password=QWElkj132!;
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - 7166:7166
        networks:
            - ecakeshopnet
        depends_on:
            - ecakeshop-sql
        links:
            - ecakeshop-sql 

networks:
  ecakeshopnet: 
    driver: bridge
