version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecakeshopnet
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ecakeshop-sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: unless-stopped
    environment:
      SA_PASSWORD: "haris***321"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    networks:
      - ecakeshopnet

  ecakeshop-api:
    restart: unless-stopped
    build: .
    environment:
      - "ConnectionStrings__eCakeShop=Server=ecakeshop-sql,1433;Database=eCakeShop;Encrypt=true;MultipleActiveResultSets=true;TrustServerCertificate=True;User=sa;Password=haris***321;"
      - "ASPNETCORE_ENVIRONMENT=Development"
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=ecakeshop@outlook.com
      - SMTP_PASSWORD=password2000
    ports:
      - "7166:7166"
    networks:
      - ecakeshopnet
    depends_on:
      - ecakeshop-sql

  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eCakeShop.Subscriber/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=ecakeshop@outlook.com
      - SMTP_PASSWORD=password2000
    depends_on:
      - rabbitmq
    networks:
      - ecakeshopnet

volumes:
  rabbitmq_data:

networks:
  ecakeshopnet:
    driver: bridge
